function k(b,a,c,d){b.v.Eb(b.ib,a,c,d,void 0)}function l(b,a,c,d){b.v.ma?k(b,a,c,d):b.v.Ae()._OnMessageFromDOM({type:"event",component:b.ib,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function aa(b,a,c){b.v.D(b.ib,a,c)}function ba(b,a){for(const [c,d]of a)aa(b,c,d)}function p(b){b.Qb||(b.v.te(b.Qd),b.Qb=!0)}window.mc=class{constructor(b,a){this.v=b;this.ib=a;this.Qb=!1;this.Qd=()=>this.Ka()}$c(){}Ka(){}};function ca(b){-1!==b.Za&&(self.clearTimeout(b.Za),b.Za=-1)}
window.qe=class{constructor(b){this.Fc=b;this.Pe=5;this.Za=-1;this.Tb=-Infinity;this.Rd=()=>{this.Za=-1;this.Tb=Date.now();this.nb=!0;this.Fc();this.nb=!1};this.td=this.nb=!1}j(){ca(this);this.Rd=this.Fc=null}};"use strict";
function da(b,a){const c=a.elementId,d=b.dd(c,a);b.da.set(c,d);d.style.boxSizing="border-box";a.isVisible||(d.style.display="none");d.addEventListener("focus",()=>{ea(b,"elem-focused",c)});d.addEventListener("blur",()=>{ea(b,"elem-blurred",c)});b.Mb&&document.body.appendChild(d)}function fa(b,a){aa(b,"get-element",c=>{const d=b.da.get(c.elementId);return a(d,c)})}function ea(b,a,c){var d;d||(d={});d.elementId=c;k(b,a,d)}
window.je=class extends self.mc{constructor(b){super(b,"progress-bar");this.da=new Map;this.Mb=!0;ba(this,[["create",a=>da(this,a)],["destroy",a=>{a=a.elementId;const c=this.da.get(a);this.Mb&&c.parentElement.removeChild(c);this.da.delete(a)}],["set-visible",a=>{this.Mb&&(this.da.get(a.elementId).style.display=a.isVisible?"":"none")}],["update-position",a=>{if(this.Mb){var c=this.da.get(a.elementId);c.style.left=a.left+"px";c.style.top=a.top+"px";c.style.width=a.width+"px";c.style.height=a.height+
"px";a=a.fontSize;null!==a&&(c.style.fontSize=a+"em")}}],["update-state",a=>{const c=this.da.get(a.elementId);this.vc(c,a)}],["focus",a=>{const c=this.da.get(a.elementId);a.focus?c.focus():c.blur()}],["set-css-style",a=>{const c=this.da.get(a.elementId),d=a.prop;a=a.val;d.startsWith("--")?c.style.setProperty(d,a):c.style[d]=a}],["set-attribute",a=>{this.da.get(a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{this.da.get(a.elementId).removeAttribute(a.name)}]]);fa(this,a=>a)}dd(){throw Error("required override");
}vc(){throw Error("required override");}};"use strict";const ha=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),t=/android/i.test(navigator.userAgent);let ia=0;function u(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Ze?new Promise(c=>{const d="c3_resolve_"+ia;++ia;self[d]=c;a.textContent=b.cf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
let la=!1,ma=!1;function na(){if(!la){try{new Worker("blob://",{get type(){ma=!0}})}catch(b){}la=!0}return ma}let v=new Audio;const oa={"audio/webm; codecs=opus":!!v.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!v.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!v.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!v.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!v.canPlayType("audio/mp4"),"audio/mpeg":!!v.canPlayType("audio/mpeg")};
v=null;async function pa(b){b=await qa(b);return(new TextDecoder("utf-8")).decode(b)}function qa(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const w=[];let y=0;window.RealFile=window.File;const B=[],C=new Map,D=new Map;let ra=0;const sa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");sa.push(b)};const ta=new Set(["cordova","playable-ad","instant-games"]);
let ua=!1;
window.Gb=class b{constructor(a){this.ma=a.ef;this.va=null;this.ba="";this.Xa=a.bf;this.Bb={};this.Qa=this.ta=null;this.Ob=[];this.J=this.wa=null;this.Nc=!1;this.xd=0;this.pb=null;this.Wa=-1;this.Ue=()=>this.He();this.Va=[];this.B=a.Sd;this.Rb="file"===location.protocol.substr(0,4);!this.ma||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&na()||(this.ma=!1);if("playable-ad"===this.B||"instant-games"===this.B)this.ma=!1;if("cordova"===this.B&&this.ma)if(t){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&
90<=parseInt(c[1],10)||(this.ma=!1)}else this.ma=!1;this.Vb=this.qa=null;"html5"!==this.B||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.D("runtime","cordova-fetch-local-file",c=>this.De(c));this.D("runtime","create-job-worker",()=>this.Ee());"cordova"===this.B?document.addEventListener("deviceready",()=>this.ld(a)):this.ld(a)}j(){this.wc();
this.va&&(this.va=this.va.onmessage=null);this.ta&&(this.ta.terminate(),this.ta=null);this.Qa&&(this.Qa.j(),this.Qa=null);this.J&&(this.J.parentElement.removeChild(this.J),this.J=null)}ne(){return ha&&"cordova"===this.B}rc(){const a=navigator.userAgent;return ha&&ta.has(this.B)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}le(){return t}fd(){return t&&ta.has(this.B)}async ld(a){"macos-wkwebview"===this.B&&this.Me();if("playable-ad"===this.B){this.qa=self.c3_base64files;this.Vb={};await this.we();
for(let d=0,e=a.$a.length;d<e;++d){var c=a.$a[d];this.Vb.hasOwnProperty(c)?a.$a[d]={Ze:!0,cf:this.Vb[c]}:this.qa.hasOwnProperty(c)&&(a.$a[d]=URL.createObjectURL(this.qa[c]))}}a.af?this.ba=a.af:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),-1!==c&&(this.ba=this.ba.substr(0,c+1)));a.gf&&(this.Bb=a.gf);c=new MessageChannel;this.va=c.port1;this.va.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>
this.Ge(d));this.pb=new self.oe(this);await va(this.pb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ma?await this.Ce(a,c.port2):await this.Be(a,c.port2)}yc(a){a=this.Bb.hasOwnProperty(a)?this.Bb[a]:a.endsWith("/workermain.js")&&this.Bb.hasOwnProperty("workermain.js")?this.Bb["workermain.js"]:
"playable-ad"===this.B&&this.qa.hasOwnProperty(a)?this.qa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async lc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.B&&this.Rb)return a=await this.Cb(d.Ye?a:this.Xa+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),
d)}return new Worker(a,d)}oa(){return Math.max(window.innerWidth,1)}ha(){return Math.max(window.innerHeight,1)}kd(a){var c=this.ba,d=location.href,e=this.oa(),f=this.ha(),g=window.devicePixelRatio,h=b.eb(),m=a.mf,q=window.cr_previewImageBlobs||this.qa,n=window.cr_previewProjectFileBlobs,z=window.cr_previewProjectFiles,x=window.kf||"";a=a.Sd;var r=(new URLSearchParams(self.location.search)).has("debug"),A=this.pb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,
isFullscreen:h,projectData:m,previewImageBlobs:q,previewProjectFileBlobs:n,previewProjectFileSWUrls:z,swClientId:x,exportType:a,isDebug:r,ife:!!self.lf,jobScheduler:{inputPort:A.Mc,outputPort:A.Tc,maxNumWorkers:A.Re},supportedAudioFormats:oa,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Xa+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Xa+"opus.wasm.wasm",isFileProtocol:this.Rb,isiOSCordova:this.ne(),isiOSWebView:this.rc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Ce(a,
c){const d=this.yc(a.ff);"preview"===this.B?(this.ta=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,m)=>{const q=n=>{this.ta.removeEventListener("message",q);n.data&&"ok"===n.data.type?h():m()};this.ta.addEventListener("message",q);this.ta.postMessage({type:"construct-worker-init","import":(new URL(d,this.ba)).toString()})})):this.ta=await this.lc(d,this.ba,{type:"module",name:"Runtime",Ye:!0});this.J=document.createElement("canvas");this.J.style.display="none";
const e=this.J.transferControlToOffscreen();document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.Zc||[],g=a.$a;f=await Promise.all(f.map(h=>this.La(h)));g=await Promise.all(g.map(h=>this.La(h)));if("cordova"===this.B)for(let h=0,m=a.ic.length;h<m;++h){const q=a.ic[h],n=q[0];if(n===a.Xc||"scriptsInEvents.js"===n||n.endsWith("/scriptsInEvents.js"))q[1]=await this.La(n)}this.ta.postMessage(Object.assign(this.kd(a),{type:"init-runtime",
isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.ic,mainProjectScript:a.Xc,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...wa(this.pb)]);this.Ob=B.map(h=>new h(this));this.jd();xa(this.wa);self.c3_callFunction=(h,m)=>{var q=this.wa;return q.v.hd(q.ib,"js-invoke-function",{name:h,params:m},void 0,void 0)};"preview"===this.B&&(self.goToLastErrorScript=()=>this.Eb("runtime","go-to-last-error-script"))}async Be(a,c){this.J=document.createElement("canvas");
this.J.style.display="none";document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Ob=B.map(g=>new g(this));this.jd();var d=a.$a.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);Array.isArray(a.Zc)&&d.unshift(...a.Zc);d=await Promise.all(d.map(g=>this.La(g)));await Promise.all(d.map(g=>u(g)));d=self.C3_ProjectScriptsStatus;const e=a.Xc,f=a.ic;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.La(h),await u(h),"preview"!==
this.B||d[g]||this.nd(g,"main script did not run to completion")}catch(m){this.nd(g,m)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.La(h),await u(h);"preview"===this.B&&"object"!==typeof self.hf.jf?(this.Jb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.kd(a),
{isInWorker:!1,messagePort:c,canvas:this.J,runOnStartupFunctions:sa}),xa(this.wa),this.md(),this.Qa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Qa,a))}nd(a,c){this.Jb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}md(){this.Jb()}Jb(){const a=window.We;a&&(a.parentElement.removeChild(a),window.We=null)}async Ee(){const a=
await ya(this.pb);return{outputPort:a,transferables:[a]}}Ae(){if(this.ma)throw Error("not available in worker mode");return this.Qa}Eb(a,c,d,e,f){this.va.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}hd(a,c,d,e,f){const g=ra++,h=new Promise((m,q)=>{D.set(g,{resolve:m,reject:q})});this.va.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Fe(a);
if("result"===c)this.Ie(a);else if("runtime-ready"===c)this.Je();else if("alert-error"===c)this.Jb(),alert(a.message);else if("creating-runtime"===c)this.md();else throw Error(`unknown message '${c}'`);}Fe(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=C.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Ib(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Ib(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,
h);this.Ib(f,!1,""+h)}):this.Ib(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Ib(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.va.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Ie(a){const c=a.responseId,d=a.isOk;a=a.result;const e=D.get(c);d?e.resolve(a):e.reject(a);D.delete(c)}D(a,c,d){let e=C.get(a);e||(e=new Map,C.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);
e.set(c,d)}static jc(a){if(B.includes(a))throw Error("DOM handler already added");B.push(a)}jd(){for(const a of this.Ob)if("runtime"===a.ib){this.wa=a;return}throw Error("cannot find runtime DOM handler");}Ge(a){this.Eb("debugger","message",a)}Je(){for(const a of this.Ob)a.$c()}static eb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ua)}static od(a){ua=!!a}te(a){this.Va.push(a);this.Dc()}Le(a){a=this.Va.indexOf(a);if(-1===a)throw Error("invalid callback");
this.Va.splice(a,1);this.Va.length||this.wc()}Dc(){-1===this.Wa&&this.Va.length&&(this.Wa=requestAnimationFrame(this.Ue))}wc(){-1!==this.Wa&&(cancelAnimationFrame(this.Wa),this.Wa=-1)}He(){this.Wa=-1;for(const a of this.Va)a();this.Dc()}Ba(a){this.wa.Ba(a)}Ja(a){this.wa.Ja(a)}Cc(){this.wa.Cc()}Hb(a){this.wa.Hb(a)}me(){return!!oa["audio/webm; codecs=opus"]}async Ne(a){a=await this.hd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}re(a){this.Nc=!0;this.xd=a}ke(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||
"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}gd(a){return!this.ke(a)}async La(a){return"cordova"===this.B&&(a.startsWith("file:")||this.Rb&&this.gd(a))?(a.startsWith(this.ba)&&(a=a.substr(this.ba.length)),a=await this.Cb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async De(a){const c=a.filename;switch(a.as){case "text":return await this.ie(c);case "buffer":return await this.Cb(c);default:throw Error("unsupported type");}}cd(a){const c=window.cordova.file.applicationDirectory+
"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async ie(a){a=await this.cd(a);return await pa(a)}xc(){if(w.length&&!(8<=y)){y++;var a=w.shift();this.xe(a.filename,a.df,a.Xe)}}Cb(a){return new Promise((c,d)=>{w.push({filename:a,df:e=>{y--;this.xc();c(e)},Xe:e=>{y--;this.xc();d(e)}});this.xc()})}async xe(a,c,d){try{const e=await this.cd(a),f=await qa(e);c(f)}catch(e){d(e)}}Me(){var a={type:"ready"};if("windows-webview2"===this.B)window.chrome.webview.postMessage(JSON.stringify(a));
else if("macos-wkwebview"===this.B)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async we(){const a=[];for(const [c,d]of Object.entries(this.qa))a.push(this.ve(c,d));await Promise.all(a)}async ve(a,c){if("object"===typeof c)this.qa[a]=new Blob([c.str],{type:c.type}),this.Vb[a]=c.str;else{let d=await this.ze(c);d||(d=this.ye(c));this.qa[a]=d}}async ze(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}ye(a){a=this.Ke(a);return this.ue(a.data,a.$e)}Ke(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{$e:a,data:d}}ue(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,m;for(m=h=0;h<e;++h)g[h]=a.charCodeAt(m++)|a.charCodeAt(m++)<<8|a.charCodeAt(m++)<<16|a.charCodeAt(m++)<<24;for(d&=
3;d--;)f[m]=a.charCodeAt(m),++m;return new Blob([f],{type:c})}};"use strict";const F=self.Gb;function za(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const Aa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),G={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Ba={dispatchUserScriptEvent:!0},H={dispatchRuntimeEvent:!0};
function Ca(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Da(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function I(b){b=URL.createObjectURL(b);try{return await Da(b)}finally{URL.revokeObjectURL(b)}}
function Ea(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Fa(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await I(b);var d=await Ea(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await I(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await I(b)}
function J(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ga=new Set(["input","textarea","datalist","select"]),Ha=new Set(["canvas","body","html"]);function K(b){Ha.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ia(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await I(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Fa(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ja=!1;document.addEventListener("pause",()=>Ja=!0);document.addEventListener("resume",()=>Ja=!1);function xa(b){b.wd=!0;b.Qc=b.v.oa();b.qb=b.v.ha()}async function Ka(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function La(b){return await self.C3_GetSvgImageSize(b.blob)}
function Ma(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}function Na(b){self.setTimeout(()=>{b.vd=!0},1E3);"cordova"===b.v.B?(document.addEventListener("pause",()=>Oa(b,!0)),document.addEventListener("resume",()=>Oa(b,!1))):document.addEventListener("visibilitychange",()=>Oa(b,document.hidden));return{isSuspended:!(!document.hidden&&!Ja)}}
function Pa(b){b.qd||(b.qd=!0,window.addEventListener("deviceorientation",a=>{b.Z||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},G)}),window.addEventListener("deviceorientationabsolute",a=>{b.Z||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},G)}))}
function Qa(b){b.pd||(b.pd=!0,window.addEventListener("devicemotion",a=>{if(!b.Z){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},G)}}))}async function Ra(b){await Ca(b.url)}
function Sa(b,a){b.yd=a.message;-1===b.Ic&&(b.Ic=setTimeout(()=>{b.Ic=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.yd)},250))}function L(b){if(!b.Z){var a=F.eb();a&&"any"!==b.Vc&&Ta(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.oa(),innerHeight:b.ha()})}}function Ua(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:F.eb(),innerWidth:b.oa(),innerHeight:b.ha()})}
function Oa(b,a){a?b.v.wc():b.v.Dc();k(b,"visibilitychange",{hidden:a})}function Va(b,a,c){"Backspace"===c.key&&K(c);if(!b.Z){var d=Aa.get(c.code)||c.code;l(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},G)}}
function Wa(b,a,c,d){b.Z||za(c)||l(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.ca,pageX:c.pageX,pageY:c.pageY+b.ca,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function Xa(b){window!==window.top&&window.focus();Ya(b.target)&&document.activeElement&&!Ya(document.activeElement)&&document.activeElement.blur()}
function M(b,a,c){if(!b.Z){if(b.yb&&"pointermove"!==a){var d=b.yb;d.nb||(ca(d),d.Tb=Date.now())}d=0;"mouse"===c.pointerType&&(d=b.vb);l(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.ca,pageX:c.pageX,pageY:c.pageY+b.ca,movementX:(c.movementX||0)+b.bc,movementY:(c.movementY||0)+b.cc,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||
0,twist:c.twist||0,timeStamp:c.timeStamp},G);b.bc=0;b.cc=0;"mouse"===c.pointerType&&(d="mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),Wa(b,d,c,Ba),b.vb=c.buttons)}}
function Za(b,a,c){if(!b.Z&&!za(c)){var d=b.vb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");l(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.ca,pageX:c.pageX,pageY:c.pageY+b.ca,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},G);b.vb=c.buttons;Wa(b,c.type,c,Ba)}}
function N(b,a,c){if(!b.Z)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];l(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.ca,pageX:f.pageX,pageY:f.pageY+b.ca,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
G)}}function $a(b,a,c){document.body.style.transform="";b.ca=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.ca=a))}}function bb(b,a,c,d){const e=b.oa(),f=b.ha();b.Ya=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:F.eb()}):10>d&&cb(b,e,f,d+1)}
function cb(b,a,c,d){-1!==b.Ya&&clearTimeout(b.Ya);b.Ya=setTimeout(()=>bb(b,a,c,d),48)}
function Ta(b){b=b.Vc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Ya(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
F.jc(class extends self.mc{constructor(b){super(b,"runtime");this.Dd=!0;this.wd=!1;this.Ya=-1;this.Vc="any";this.pd=this.qd=!1;this.Ea=null;this.Z=!1;this.yd="";this.Ic=-1;this.Pa=this.yb=null;this.cc=this.bc=0;this.vd=!1;this.Qc=b.oa();this.qb=b.ha();this.ca=this.Ab=0;b.D("canvas","update-size",d=>{var e=this.v;e.Nc||(e=e.J,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",
d.displayScale),this.Dd&&(e.style.display="",this.Dd=!1))});b.D("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.D("runtime","raster-svg-image",d=>Ka(d));b.D("runtime","get-svg-image-size",d=>La(d));b.D("runtime","set-target-orientation",d=>{this.Vc=d.targetOrientation});b.D("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.D("runtime",
"post-to-debugger",d=>Ma(d));b.D("runtime","go-to-script",d=>Ma(d));b.D("runtime","before-start-ticking",()=>Na(this));b.D("runtime","debug-highlight",d=>{if(d.show){this.Ea||(this.Ea=document.createElement("div"),this.Ea.id="inspectOutline",document.body.appendChild(this.Ea));var e=this.Ea;e.style.display="";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Ea&&(this.Ea.style.display="none")});b.D("runtime",
"enable-device-orientation",()=>Pa(this));b.D("runtime","enable-device-motion",()=>Qa(this));b.D("runtime","add-stylesheet",d=>Ra(d));b.D("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.D("runtime","alert",d=>{alert(d.message)});b.D("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.D("runtime","set-exporting-to-video",d=>{this.Z=!0;const e=
document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.v.J.style.display="";this.v.re(d.duration)});b.D("runtime","export-to-video-progress",d=>Sa(this,d));b.D("runtime","exported-to-video",d=>{window.Ve({type:"exported-video",blob:d.blob,time:d.time})});b.D("runtime","exported-to-image-sequence",d=>{window.Ve({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input",
"textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||J(e)||d.preventDefault()});const c=b.J;window.addEventListener("selectstart",K);window.addEventListener("gesturehold",K);c.addEventListener("selectstart",K);c.addEventListener("gesturehold",K);window.addEventListener("touchstart",K,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",K,{passive:!1}),c.addEventListener("pointerdown",K)):c.addEventListener("touchstart",
K);this.vb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ia,{passive:!1});window.addEventListener("wheel",Ia,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.Z&&this.wd){var d=this.oa();var e=this.ha();if(this.v.fd()){if(this.vd){if(this.Qc===d&&e<this.qb){this.Ab=this.qb-e;$a(this,this.qb,this.Ab);d=void 0;break a}0<this.Ab&&(this.Ab=0,$a(this,e,this.Ab))}this.Qc=d;this.qb=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,
devicePixelRatio:window.devicePixelRatio,isFullscreen:F.eb()});this.v.rc()&&(-1!==this.Ya&&clearTimeout(this.Ya),bb(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>L(this));window.addEventListener("webkitfullscreenchange",()=>L(this));window.addEventListener("mozfullscreenchange",()=>L(this));window.addEventListener("fullscreenerror",d=>Ua(this,d));window.addEventListener("webkitfullscreenerror",d=>Ua(this,d));window.addEventListener("mozfullscreenerror",d=>Ua(this,
d));if(b.rc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):J(f)}else d=!1}d||(document.scrollingElement.scrollTop=
0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(F.od(!0),L(this)):"exited-fullscreen"===d?(F.od(!1),L(this)):console.warn("Unknown wrapper message: ",d)};this.Ra=new Set;this.Xb=new WeakSet;this.ua=!1}$c(){window.addEventListener("focus",()=>{k(this,"window-focus",null,H)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}k(this,"window-blur",{parentHasFocus:a},H);this.vb=0});window.addEventListener("focusin",a=>{a=a.target;(Ga.has(a.tagName.toLowerCase())||
J(a))&&k(this,"keyboard-blur",null,H)});window.addEventListener("keydown",a=>Va(this,"keydown",a));window.addEventListener("keyup",a=>Va(this,"keyup",a));window.addEventListener("dblclick",a=>Wa(this,"dblclick",a,G));window.addEventListener("wheel",a=>{this.Z||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.ca,pageX:a.pageX,pageY:a.pageY+this.ca,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},G)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
a=>{Xa(a);M(this,"pointerdown",a)}),this.v.ma&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.yb=new self.qe(()=>{M(this,"pointermove",this.Pa);this.Pa=null}),this.yb.td=!0,window.addEventListener("pointerrawupdate",a=>{this.Pa&&(this.bc+=this.Pa.movementX||0,this.cc+=this.Pa.movementY||0);this.Pa=a;a=this.yb;if(-1===a.Za){var c=Date.now(),d=c-a.Tb,e=a.Pe;d>=e&&a.td?(a.Tb=c,a.nb=!0,a.Fc(),a.nb=!1):a.Za=self.setTimeout(a.Rd,Math.max(e-d,4))}})):window.addEventListener("pointermove",
a=>M(this,"pointermove",a)),window.addEventListener("pointerup",a=>M(this,"pointerup",a)),window.addEventListener("pointercancel",a=>M(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{Xa(a);Za(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>Za(this,"pointermove",a)),window.addEventListener("mouseup",a=>Za(this,"pointerup",a)),window.addEventListener("touchstart",a=>{Xa(a);N(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>N(this,"pointermove",a)),window.addEventListener("touchend",
a=>N(this,"pointerup",a)),window.addEventListener("touchcancel",a=>N(this,"pointercancel",a)));const b=()=>this.Cc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.v.le()&&!this.v.fd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{$a(this,this.ha(),
navigator.virtualKeyboard.boundingRect.height)}))}oa(){return this.v.oa()}ha(){return this.v.ha()}Cc(){var b=[...this.Ra];this.Ra.clear();if(!this.ua)for(const a of b)(b=a.play())&&b.catch(()=>{this.Xb.has(a)||this.Ra.add(a)})}Ba(b){if("function"!==typeof b.play)throw Error("missing play function");this.Xb.delete(b);let a;try{a=b.play()}catch(c){this.Ra.add(b);return}a&&a.catch(()=>{this.Xb.has(b)||this.Ra.add(b)})}Ja(b){this.Ra.delete(b);this.Xb.add(b)}Hb(b){this.ua=!!b}});"use strict";
async function va(b){if(b.Oe)throw Error("already initialised");b.Oe=!0;var a=b.xa.yc(("playable-ad"===b.xa.B?b.xa.Xa:"")+"dispatchworker.js");b.Hc=await b.xa.lc(a,b.hb,{name:"DispatchWorker"});a=new MessageChannel;b.Mc=a.port1;b.Hc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Tc=await ya(b)}function wa(b){return[b.Mc,b.Tc]}
async function ya(b){const a=b.Ed.length;var c=b.xa.yc(("playable-ad"===b.xa.B?b.xa.Xa:"")+"jobworker.js");c=await b.xa.lc(c,b.hb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Hc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Ed.push(c);return e.port1}
self.oe=class{constructor(b){this.xa=b;this.hb=b.ba;this.hb="preview"===b.B?this.hb+"workers/":this.hb+b.Xa;this.Re=Math.min(navigator.hardwareConcurrency||2,16);this.Hc=null;this.Ed=[];this.Tc=this.Mc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Gb({ef:!0,ff:"workermain.js",$a:["scripts/c3runtime.js"],ic:[],Xc:"",bf:"scripts/",Zc:[],Sd:"html5"}));"use strict";function O(b){b.stopPropagation()}
self.Gb.jc(class extends self.je{constructor(b){super(b)}dd(b,a){const c=document.createElement("progress");c.style.position="absolute";c.style.userSelect="none";c.style.webkitUserSelect="none";c.addEventListener("pointerdown",O);c.addEventListener("pointermove",O);c.addEventListener("pointerrawupdate",O);c.addEventListener("pointerup",O);c.addEventListener("mousedown",O);c.addEventListener("mouseup",O);c.addEventListener("click",()=>{var d;d||(d={});d.elementId=b;l(this,"click",d)});a.id&&(c.id=
a.id);a.className&&(c.className=a.className);this.vc(c,a);return c}vc(b,a){b.title=a.title;const c=a.value;a=a.max;0<a&&0<=c?(b.max=a,b.value=c):(b.removeAttribute("value"),b.removeAttribute("max"))}});"use strict";const db=180/Math.PI;
async function eb(b,a){if(a.isiOSCordova||a.isSafari)b.$b=!0;b.Wc=a.timeScaleMode;b.Jd=["equalpower","HRTF","soundfield"][a.panningModel];b.ud=["linear","inverse","exponential"][a.distanceModel];b.Kd=a.refDistance;b.Id=a.maxDistance;b.Md=a.rolloffFactor;if(b.v.Nc)b.$b=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.v.xd)});else{var c={latencyHint:a.latencyHint};b.Pd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");fb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&fb(b);k(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Na=b.g.createGain();b.Na.connect(b.g.destination);c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
P(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function gb(b,a){var c=a.originalUrl;const d=a.url,e=a.type,f=a.isMusic,g=a.tag,h=a.isLooping,m=a.vol,q=a.pos,n=a.panning,z=a.stereoPan;let x=a.off;0<x&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+b.g.currentTime);b.Fd=g;hb(b,g);try{b.$=await ib(b,c,d,e,g,f);if(n){Q(b.$,!0);var r=b.$,A=n.innerAngle,ja=n.outerAngle,ka=n.outerGain;if(r.ob){jb(r,n.x,n.y,n.angle);var E=self.ab.se;r.ra[0]!==E(A)&&(r.ra[0]=E(A),
r.F.coneInnerAngle=E(A));r.ra[1]!==E(ja)&&(r.ra[1]=E(ja),r.F.coneOuterAngle=E(ja));r.ra[2]!==ka&&(r.ra[2]=ka,r.F.coneOuterGain=ka)}n.hasOwnProperty("uid")&&(b.$.pa=n.uid)}else"number"===typeof z&&0!==z?(R(b.$,!0),kb(b.$,z)):(Q(b.$,!1),R(b.$,!1));b.$.Play(h,m,q,x)}catch(vb){console.error("[Construct] Audio: error starting playback: ",vb);return}finally{c=b.xb.get(g);if(!c)throw Error("expected pending tag");c.Yc--;0===c.Yc&&(c.resolve(),b.xb.delete(g))}p(b)}
async function lb(b,a){var c=a.tag;const d=a.vol,e=a.duration;a=a.stopOnEnd;await mb(b,c);for(const n of S(b,c)){c=n;var f=d,g=e,h=a;if(!c.Oa){var m=c.G.gain;m.cancelScheduledValues(0);var q=c.s.g.currentTime;g=q+g;m.setValueAtTime(m.value,q);m.linearRampToValueAtTime(f,g);c.Ha=f;c.lb=g;c.Od=h}}T(b)}async function nb(b,a){const c=a.tag;a=a.rate;await mb(b,c);for(const d of S(b,c))b=d,b.la!==a&&(b.la=a,b.Ca())}
async function ob(b,a){const c=a.tag;a=a.pos;await mb(b,c);for(const d of S(b,c))d.sc(a)}async function pb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await ib(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function qb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ja.indexOf(a),-1!==a&&b.ja.splice(a,1)}
async function rb(b,a){var c=a.type,d=a.tag,e=a.params;if("filter"===c)e=new self.Yd(b,...e);else if("delay"===c)e=new self.Wd(b,...e);else if("convolution"===c){c=null;try{c=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(g){console.log("[Construct] Audio: error loading convolution: ",g);return}c=e=new self.Vd(b,c.ia,...e);var f=a.bufferType;c.rd=a.bufferOriginalUrl;c.sd=f}else if("flanger"===c)e=new self.Zd(b,...e);else if("phaser"===c)e=new self.ae(b,...e);else if("gain"===c)e=
new self.$d(b,...e);else if("stereopan"===c)e=new self.ce(b,...e);else if("tremolo"===c)e=new self.de(b,...e);else if("ringmod"===c)e=new self.be(b,...e);else if("distortion"===c)e=new self.Xd(b,...e);else if("compressor"===c)e=new self.Ud(b,...e);else if("analyser"===c)e=new self.Td(b,...e);else throw Error("invalid effect type");a=e;d=d.toLowerCase();e=b.ka.get(d);e||(e=[],b.ka.set(d,e));a.Cd=e.length;a.fa=d;e.push(a);sb(b,d);tb(b)}
async function ub(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(const e of b.I)e.za()&&1===c||!e.za()&&2===c?d.push(e):e.j();b.I=d}for(const e of b.ka.values())for(const f of e)f.j();b.ka.clear();b.fc=a.timeScale;b.Jc=a.gameTime;d=a.listenerPos;b.aa[0]=d[0];b.aa[1]=d[1];b.aa[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);b.ua=a.isSilent;b.v.Hb(b.ua);b.Wb=a.masterVolume;b.Na.gain.value=b.Wb;d=[];for(const e of Object.values(a.effects))d.push(Promise.all(e.map(f=>rb(b,f))));await Promise.all(d);
await Promise.all(a.playing.map(e=>wb(b,e,c)));T(b)}async function xb(b,a){try{const c=b.g.suspend(a.time);b.Bd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.v.Eb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>yb(d)),b.Bd=!0);await c}catch(c){yb(c)}}
function fb(b){b.Pb||(b.Lc=!1,window.addEventListener("pointerup",b.ya,!0),window.addEventListener("touchend",b.ya,!0),window.addEventListener("click",b.ya,!0),window.addEventListener("keydown",b.ya,!0),b.Pb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ja)if(g.cb()===c)return await zb(g),g;if(f)return null;if(e&&(b.$b||b.Ad)){f=0;for(let h=0,m=b.ja.length;h<m;++h)g=b.ja[h],b.ja[f]=g,g.za()?g.j():++f;b.ja.length=f}f="audio/webm; codecs=opus"===d&&!b.Pd;e&&f&&(b.Ad=!0);c=!e||b.$b||f?new self.ge(b,a,c,d,e,f):new self.ee(b,a,c,d,e);b.ja.push(c);await zb(c);b.Hd.has(a)||(k(b,"buffer-metadata",{originalUrl:a,duration:c.ga()}),b.Hd.add(a));return c}
function Ab(b,a){return(a=b.ka.get(a.toLowerCase()))?a[0].N():b.na()}function sb(b,a){let c=b.na();var d=b.ka.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.S(b.na()):e.S(d[f+1].N())}}for(const f of S(b,a))d=c,e=f.ea||f.F||f.G,e.disconnect(),e.connect(d);b.Fa&&b.Rc===a&&(b.Fa.disconnect(),b.Fa.connect(c))}
function*S(b,a){if(a)for(const c of b.I)b=c.fa,(b.length!==a.length?0:b===a||b.toLowerCase()===a.toLowerCase())&&(yield c);else b.$&&!b.$.U()&&(yield b.$)}function Bb(b,a,c){return c?b.v.Ne(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Cb(b,a){let c=0;for(let d=0,e=b.I.length;d<e;++d){const f=b.I[d];b.I[c]=f;f.O===a?f.j():++c}b.I.length=c}
async function ib(b,a,c,d,e,f){for(const g of b.I)if(g.cb()===c&&(g.kc()||f))return g.fa=e,g;a=await P(b,a,c,d,f);e="html5"===a.Ec?new self.fe(a.s,a,e):new self.he(a.s,a,e);b.I.push(e);return e}function hb(b,a){let c=b.xb.get(a);if(!c){let d=null;c={Yc:0,promise:new Promise(e=>d=e),resolve:d};b.xb.set(a,c)}c.Yc++}function mb(b,a){a||(a=b.Fd);return(b=b.xb.get(a))?b.promise:Promise.resolve()}function T(b){if(0<b.Ma.size)p(b);else for(const a of b.I)if(!a.H&&!a.U()){p(b);break}}
function Db(b,a,c,d){k(b,"trigger",{type:a,tag:c,aiid:d})}function tb(b){b.Oc||(b.Oc=!0,Promise.resolve().then(()=>Eb(b)))}function Eb(b){const a={};for(const [c,d]of b.ka)a[c]=d.map(e=>e.bb());k(b,"fxstate",{fxstate:a});b.Oc=!1}
async function wb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tag,m=a.isLooping,q=a.volume,n=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await ib(b,d,e,f,h,g)}catch(z){console.error("[Construct] Audio: error loading audio state: ",z);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.Ta[0]=f[0],b.Ta[1]=f[1],b.Ta[2]=f[2],f=d.orient,b.Sa[0]=f[0],b.Sa[1]=f[1],b.Sa[2]=f[2],e.setPosition(...b.Ta),e.setOrientation(...b.Sa),b.ra[0]=d.cia,b.ra[1]=d.coa,b.ra[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.pa=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),kb(b,d));c.Play(m,q,n,0);a.isPlaying||c.fb();c.Ac(a)}}}function yb(b){console.error("[Audio] Offline rendering error: ",b)}
self.ab=class extends self.mc{constructor(b){super(b,"audio");this.Na=this.g=null;this.Pb=this.Lc=!1;this.ya=()=>{if(!this.Lc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Pb&&(this.Lc=!0,window.removeEventListener("pointerup",this.ya,!0),window.removeEventListener("touchend",this.ya,!0),window.removeEventListener("click",this.ya,!0),window.removeEventListener("keydown",
this.ya,!0),this.Pb=!1)}};this.ja=[];this.I=[];this.$=null;this.Fd="";this.Hd=new Set;this.Gd=-1;this.xb=new Map;this.Wb=1;this.ua=!1;this.Wc=0;this.fc=1;this.Jc=0;this.Jd="HRTF";this.ud="inverse";this.Kd=600;this.Id=1E4;this.Md=1;this.aa=[0,0,0];this.Ad=this.$b=!1;this.Pd=this.v.me();this.ka=new Map;this.Ma=new Set;this.Bd=this.Oc=!1;this.Rc="";this.Fa=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Fa&&this.Fa.disconnect();this.Rc=c.toLowerCase();this.Fa=this.g.createMediaStreamSource(a);this.Fa.connect(Ab(this,
this.Rc))};this.Nb=null;self.C3Audio_GetOutputStream=()=>{this.Nb||(this.Nb=this.g.createMediaStreamDestination(),this.Na.connect(this.Nb));return this.Nb.stream};self.C3Audio_DOMInterface=this;ba(this,[["create-audio-context",a=>eb(this,a)],["play",a=>gb(this,a)],["stop",a=>{a=a.tag;for(const c of S(this,a))c.Aa()}],["stop-all",()=>{for(const a of this.I)a.Aa()}],["set-paused",a=>{const c=a.tag;a=a.paused;for(const d of S(this,c))a?d.fb():d.Fb();T(this)}],["set-volume",a=>{const c=a.tag;a=a.vol;
for(const d of S(this,c))U(d,a)}],["fade-volume",a=>lb(this,a)],["set-master-volume",a=>{this.Wb=a.vol;this.Na.gain.value=this.Wb}],["set-muted",a=>{const c=a.tag;a=a.isMuted;for(const d of S(this,c))Fb(d,a)}],["set-silent",a=>{this.ua=a.isSilent;this.v.Hb(this.ua);for(const c of this.I)c.Kb()}],["set-looping",a=>{const c=a.tag;a=a.isLooping;for(const d of S(this,c))d.tc(a)}],["set-playback-rate",a=>nb(this,a)],["set-stereo-pan",a=>{const c=a.tag;a=a.p;for(const d of S(this,c))R(d,!0),kb(d,a)}],["seek",
a=>ob(this,a)],["preload",a=>pb(this,a)],["unload",a=>qb(this,a)],["unload-all",()=>{for(const a of this.ja)a.j();this.ja.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.I)c.uc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>rb(this,a)],["set-effect-param",a=>{const c=a.index,d=a.param,e=a.value,f=a.ramp,g=a.time;a=this.ka.get(a.tag);!a||0>c||c>=a.length||(a[c].Y(d,e,f,g),tb(this))}],["remove-effects",a=>{a=a.tag.toLowerCase();const c=
this.ka.get(a);if(c&&c.length){for(const d of c)d.j();this.ka.delete(a);sb(this,a)}}],["tick",a=>{this.fc=a.timeScale;this.Jc=a.gameTime;this.Gd=a.tickCount;if(0!==this.Wc)for(var c of this.I)c.Ca();!(c=a.listenerPos)||this.aa[0]===c[0]&&this.aa[1]===c[1]&&this.aa[2]===c[2]||(this.aa[0]=c[0],this.aa[1]=c[1],this.aa[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));for(const d of a.instPans){a=d.uid;for(const e of this.I)e.pa===a&&jb(e,d.x,d.y,d.angle)}}],["load-state",a=>ub(this,a)],["offline-render-audio",
a=>xb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}na(){return this.Na}Db(){return this.ua}Ba(b){this.v.Ba(b)}Ja(b){this.v.Ja(b)}Ka(){for(var b of this.Ma)b.Ka();b=this.g.currentTime;for(var a of this.I)a.Ka(b);a=this.I.filter(c=>!c.H&&!c.U()).map(c=>c.bb());k(this,"state",{tickCount:this.Gd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ma].map(c=>({tag:c.fa,index:c.Cd,peak:c.Ua,rms:c.Ld,binCount:c.l.frequencyBinCount,freqBins:c.zd}))});
0===a.length&&0===this.Ma.size&&this.Qb&&(this.v.Le(this.Qd),this.Qb=!1)}static se(b){return b*db}static ed(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static pe(b){return Math.log(Math.max(Math.min(b,1),0))/Math.log(10)*20}};self.Gb.jc(self.ab);"use strict";function zb(b){b.Ub||(b.Ub=b.zc());return b.Ub}self.ad=class{constructor(b,a,c,d,e){this.s=b;this.Te=a;this.Ga=c;this.R=d;this.Qe=e;this.Ec="";this.Ub=null}j(){this.Ub=this.s=null}zc(){}V(){return this.s.V()}oc(){return this.Te}cb(){return this.Ga}nc(){return this.R}za(){return this.Qe}ga(){}};
"use strict";
self.ee=class extends self.ad{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Ec="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.rb=this.sb=null;this.M.addEventListener("canplaythrough",()=>!0);this.wb=this.V().createGain();this.ub=null;this.M.addEventListener("canplay",()=>{this.sb&&(this.sb(),this.rb=this.sb=null);!this.ub&&this.M&&(this.ub=this.V().createMediaElementSource(this.M),this.ub.connect(this.wb))});this.onended=null;this.M.addEventListener("ended",()=>
{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ga}' error: `,f);this.rb&&(this.rb(f),this.rb=this.sb=null)})}j(){Cb(this.s,this);this.wb.disconnect();this.wb=null;this.ub.disconnect();this.ub=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}zc(){return new Promise((b,a)=>{this.sb=b;this.rb=a;this.M.src=this.Ga})}T(){return this.M}ga(){return this.M.duration}};"use strict";
async function Hb(b){if(b.Da)return b.Da;var a=b.s.v;if("cordova"===a.B&&a.gd(b.Ga)&&a.Rb)b.Da=await a.Cb(b.Ga);else{a=await fetch(b.Ga);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Da=await a.arrayBuffer()}}async function Ib(b){if(b.ia)return b.ia;b.ia=await Bb(b.s,b.Da,b.Se);b.Da=null}
self.ge=class extends self.ad{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Ec="webaudio";this.ia=this.Da=null;this.Se=!!f}j(){Cb(this.s,this);this.ia=this.Da=null;super.j()}async zc(){try{await Hb(this),await Ib(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ga}': `,b)}}ga(){return this.ia?this.ia.duration:0}};"use strict";let Jb=0;
function Q(b,a){a=!!a;b.ob!==a&&(b.ob=a,b.ob?(R(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.s.Jd,b.F.distanceModel=b.s.ud,b.F.refDistance=b.s.Kd,b.F.maxDistance=b.s.Id,b.F.rolloffFactor=b.s.Md),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.na())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.na())))}
function R(b,a){a=!!a;b.Sb!==a&&(b.Sb=a,b.Sb?(Q(b,!1),b.ea=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.ea),b.ea.connect(b.na())):(b.ea.disconnect(),b.ea=null,b.G.disconnect(),b.G.connect(b.na())))}function kb(b,a){b.Sb&&b.Uc!==a&&(b.ea.pan.value=a,b.Uc=a)}function U(b,a){b.Ha=a;b.G.gain.cancelScheduledValues(0);b.lb=-1;b.G.gain.value=b.pc()}function Fb(b,a){a=!!a;b.Oa!==a&&(b.Oa=a,b.Kb())}
function jb(b,a,c,d){if(b.ob){var e=b.Ta,f=b.Sa,g=Math.cos(d);d=Math.sin(d);if(e[0]!==a||e[1]!==c||0!==e[2])e[0]=a,e[1]=c,e[2]=0,b.F.setPosition(...e);if(f[0]!==g||f[1]!==d||0!==f[2])f[0]=g,f[1]=d,f[2]=0,b.F.setOrientation(...f)}}function V(b){return b.Pc?b.s.Jc:performance.now()/1E3}
self.bd=class{constructor(b,a,c){this.s=b;this.O=a;this.fa=c;this.Lb=Jb++;this.G=this.V().createGain();this.G.connect(this.na());this.F=null;this.ob=!1;this.Ta=[0,0,0];this.Sa=[0,0,0];this.ra=[0,0,0];this.ea=null;this.Sb=!1;this.Uc=0;this.H=!0;this.X=this.sa=this.K=!1;this.Ha=1;this.Oa=!1;this.la=1;b=this.s.Wc;this.Pc=1===b&&!this.za()||2===b;this.lb=this.pa=-1;this.Od=!1}j(){this.O=this.s=null;this.F&&(this.F.disconnect(),this.F=null);this.ea&&(this.ea.disconnect(),this.ea=null);this.G.disconnect();
this.G=null}V(){return this.s.V()}na(){return Ab(this.s,this.fa)}oc(){return this.O.oc()}cb(){return this.O.cb()}nc(){return this.O.nc()}za(){return this.O.za()}U(){}kc(){}IsPlaying(){return!this.H&&!this.K&&!this.U()}Ia(){}ga(){return this.O.ga()}Play(){}Aa(){}fb(){}Fb(){}Ka(b){-1!==this.lb&&b>=this.lb&&(this.lb=-1,this.Od&&this.Aa(),Db(this.s,"fade-ended",this.fa,this.Lb))}pc(){const b=this.Ha;return isFinite(b)?b:0}Db(){return this.s.Db()}Kb(){}tc(){}Ca(){}sc(){}uc(){}qc(){}bb(){var b=this.Lb,
a=this.fa,c=this.ga(),d=this.Ha,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Ta,orient:this.Sa,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.pa}}else f=null;return{aiid:b,tag:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ia(),playbackRate:this.la,uid:this.pa,bufferOriginalUrl:this.oc(),bufferUrl:"",bufferType:this.nc(),isMusic:this.za(),isLooping:this.X,isMuted:this.Oa,resumePosition:this.qc(),pan:f,stereoPan:this.ea?this.Uc:null}}Ac(b){var a=b.playbackRate;
this.la!==a&&(this.la=a,this.Ca());Fb(this,b.isMuted)}};"use strict";
self.fe=class extends self.bd{constructor(b,a,c){super(b,a,c);this.O.wb.connect(this.G);this.O.onended=()=>this.Bc()}j(){this.Aa();this.O.wb.disconnect();super.j()}T(){return this.O.T()}Bc(){this.H=!0;this.pa=-1;Db(this.s,"ended",this.fa,this.Lb)}U(){return this.T().ended}kc(){return this.H?!0:this.U()}Ia(){let b=this.T().currentTime;this.X||(b=Math.min(b,this.ga()));return b}Play(b,a,c){const d=this.T();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.O.cb()}' to position '${c}': `,e)}this.s.Ba(d);this.K=this.H=!1;this.X=b;this.la=1}Aa(){const b=this.T();b.paused||b.pause();this.s.Ja(b);this.H=!0;this.K=!1;this.pa=-1}fb(){if(!(this.K||this.H||this.U())){var b=this.T();b.paused||b.pause();this.s.Ja(b);this.K=!0}}Fb(){!this.K||this.H||this.U()||(this.s.Ba(this.T()),this.K=!1)}Kb(){this.T().muted=this.Oa||this.Db()}tc(b){b=!!b;this.X!==b&&(this.X=
b,this.T().loop=b)}Ca(){let b=this.la;this.Pc&&(b*=this.s.fc);try{this.T().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}sc(b){if(!this.H&&!this.U())try{this.T().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}qc(){return this.Ia()}uc(b){b?this.IsPlaying()?(this.T().pause(),this.sa=!0):this.sa=!1:this.sa&&(this.s.Ba(this.T()),this.sa=!1)}};"use strict";function W(b){b.o&&b.o.disconnect();b.o=null;b.gb=null}
self.he=class extends self.bd{constructor(b,a,c){super(b,a,c);this.o=null;this.Yb=d=>this.Bc(d);this.Kc=!0;this.gb=null;this.P=this.Zb=this.ac=0;this.Sc=1}j(){this.Aa();W(this);this.Yb=null;super.j()}Bc(b){this.K||this.sa||b.target!==this.gb||(this.H=this.Kc=!0,this.pa=-1,W(this),Db(this.s,"ended",this.fa,this.Lb))}U(){return!this.H&&this.o&&this.o.loop||this.K?!1:this.Kc}kc(){return!this.o||this.H?!0:this.U()}Ia(){let b;b=this.K?this.P:this.Zb+(V(this)-this.ac)*this.la;this.X||(b=Math.min(b,this.ga()));
return b}Play(b,a,c,d){this.Sc=1;U(this,a);W(this);this.o=this.V().createBufferSource();this.o.buffer=this.O.ia;this.o.connect(this.G);this.gb=this.o;this.o.onended=this.Yb;this.o.loop=b;this.o.start(d,c);this.K=this.H=this.Kc=!1;this.X=b;this.la=1;this.ac=V(this);this.Zb=c}Aa(){if(this.o)try{this.o.stop(0)}catch(b){}this.H=!0;this.K=!1;this.pa=-1}fb(){this.K||this.H||this.U()||(this.P=this.Ia(),this.X&&(this.P%=this.ga()),this.K=!0,this.o.stop(0))}Fb(){!this.K||this.H||this.U()||(W(this),this.o=
this.V().createBufferSource(),this.o.buffer=this.O.ia,this.o.connect(this.G),this.gb=this.o,this.o.onended=this.Yb,this.o.loop=this.X,U(this,this.Ha),this.Ca(),this.o.start(0,this.P),this.ac=V(this),this.Zb=this.P,this.K=!1)}pc(){return super.pc()*this.Sc}Kb(){this.Sc=this.Oa||this.Db()?0:1;U(this,this.Ha)}tc(b){b=!!b;this.X!==b&&(this.X=b,this.o&&(this.o.loop=b))}Ca(){let b=this.la;this.Pc&&(b*=this.s.fc);this.o&&(this.o.playbackRate.value=b)}sc(b){this.H||this.U()||(this.K?this.P=b:(this.fb(),this.P=
b,this.Fb()))}qc(){return this.P}uc(b){b?this.IsPlaying()?(this.sa=!0,this.P=this.Ia(),this.X&&(this.P%=this.ga()),this.o.stop(0)):this.sa=!1:this.sa&&(W(this),this.o=this.V().createBufferSource(),this.o.buffer=this.O.ia,this.o.connect(this.G),this.gb=this.o,this.o.onended=this.Yb,this.o.loop=this.X,U(this,this.Ha),this.Ca(),this.o.start(0,this.P),this.ac=V(this),this.Zb=this.P,this.sa=!1)}Ac(b){super.Ac(b);this.P=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.s=b;this.g=b.V();this.Cd=-1;this.R=this.fa="";this.m=null}j(){this.g=null}N(){}S(){}bb(){return{type:this.R,tag:this.fa,params:this.m}}}
self.Yd=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.R="filter";this.m=[a,c,d,e,f,g];this.u=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.C=this.g.createBiquadFilter();this.C.type=a;this.C.frequency.value=c;this.C.detune.value=d;this.C.Q.value=e;this.C.gain.vlaue=f;this.u.connect(this.C);this.u.connect(this.h);this.C.connect(this.i)}j(){this.u.disconnect();this.C.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;Y(this,this.C.frequency,a,c,d);break;case 2:this.m[2]=a;Y(this,this.C.detune,a,c,d);break;case 3:this.m[3]=a;Y(this,this.C.Q,a,c,d);break;case 4:this.m[4]=a,Y(this,this.C.gain,a,c,d)}}};
self.Wd=class extends Z{constructor(b,a,c,d){super(b);this.R="delay";this.m=[a,c,d];this.u=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.tb=X(this);this.W=this.g.createDelay(a);this.W.delayTime.value=a;this.kb=X(this);this.kb.gain.value=c;this.u.connect(this.tb);this.u.connect(this.h);this.tb.connect(this.i);this.tb.connect(this.W);this.W.connect(this.kb);this.kb.connect(this.tb)}j(){this.u.disconnect();this.i.disconnect();this.h.disconnect();this.tb.disconnect();
this.W.disconnect();this.kb.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){const e=self.ab.ed;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);Y(this,this.kb.gain,e(a),c,d);break;case 5:this.m[0]=a,Y(this,this.W.delayTime,a,c,d)}}};
self.Vd=class extends Z{constructor(b,a,c,d){super(b);this.R="convolution";this.m=[c,d];this.sd=this.rd="";this.u=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.jb=this.g.createConvolver();this.jb.normalize=c;this.jb.buffer=a;this.u.connect(this.jb);this.u.connect(this.h);this.jb.connect(this.i)}j(){this.u.disconnect();this.jb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}bb(){const b=super.bb();b.bufferOriginalUrl=this.rd;b.bufferUrl="";b.bufferType=this.sd;return b}};
self.Zd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.R="flanger";this.m=[a,c,d,e,f];this.u=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.mb=X(this);this.mb.gain.value=e;this.W=this.g.createDelay(a+c);this.W.delayTime.value=a;this.A=this.g.createOscillator();this.A.frequency.value=d;this.L=X(this);this.L.gain.value=c;this.u.connect(this.W);this.u.connect(this.h);this.W.connect(this.i);this.W.connect(this.mb);this.mb.connect(this.W);this.A.connect(this.L);
this.L.connect(this.W.delayTime);this.A.start(0)}j(){this.A.stop(0);this.u.disconnect();this.W.disconnect();this.A.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.mb.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;Y(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;Y(this,this.A.frequency,a,c,d);break;case 8:this.m[3]=a/100,Y(this,this.mb.gain,a/100,c,d)}}};
self.ae=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.R="phaser";this.m=[a,c,d,e,f,g];this.u=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.C=this.g.createBiquadFilter();this.C.type="allpass";this.C.frequency.value=a;this.C.detune.value=c;this.C.Q.value=d;this.A=this.g.createOscillator();this.A.frequency.value=f;this.L=X(this);this.L.gain.value=e;this.u.connect(this.C);this.u.connect(this.h);this.C.connect(this.i);this.A.connect(this.L);this.L.connect(this.C.frequency);
this.A.start(0)}j(){this.A.stop(0);this.u.disconnect();this.C.disconnect();this.A.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;Y(this,this.C.frequency,a,c,d);break;case 2:this.m[1]=a;Y(this,this.C.detune,a,c,d);
break;case 3:this.m[2]=a;Y(this,this.C.Q,a,c,d);break;case 6:this.m[3]=a;Y(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,Y(this,this.A.frequency,a,c,d)}}};self.$d=class extends Z{constructor(b,a){super(b);this.R="gain";this.m=[a];this.l=X(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){const e=self.ab.ed;switch(b){case 4:this.m[0]=e(a),Y(this,this.l.gain,e(a),c,d)}}};
self.ce=class extends Z{constructor(b,a){super(b);this.R="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,Y(this,this.l.pan,a,c,d)}}};
self.de=class extends Z{constructor(b,a,c){super(b);this.R="tremolo";this.m=[a,c];this.l=X(this);this.l.gain.value=1-c/2;this.A=this.g.createOscillator();this.A.frequency.value=a;this.L=X(this);this.L.gain.value=c/2;this.A.connect(this.L);this.L.connect(this.l.gain);this.A.start(0)}j(){this.A.stop(0);this.A.disconnect();this.L.disconnect();this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;Y(this,this.l.gain,1-a/2,c,d);Y(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,Y(this,this.A.frequency,a,c,d)}}};
self.be=class extends Z{constructor(b,a,c){super(b);this.R="ringmod";this.m=[a,c];this.u=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.zb=X(this);this.zb.gain.value=0;this.A=this.g.createOscillator();this.A.frequency.value=a;this.A.connect(this.zb.gain);this.A.start(0);this.u.connect(this.zb);this.u.connect(this.h);this.zb.connect(this.i)}j(){this.A.stop(0);this.A.disconnect();this.zb.disconnect();this.u.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,Y(this,this.A.frequency,a,c,d)}}};
self.Xd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.R="distortion";this.m=[a,c,d,e,f];this.u=X(this);this.ec=X(this);this.dc=X(this);b=d;.01>b&&(b=.01);this.ec.gain.value=b;this.dc.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.hc=this.g.createWaveShaper();this.Gc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Gc[32768+e]=f,this.Gc[32768-
e-1]=-f;this.hc.curve=this.Gc;this.u.connect(this.ec);this.u.connect(this.h);this.ec.connect(this.hc);this.hc.connect(this.dc);this.dc.connect(this.i)}j(){this.u.disconnect();this.ec.disconnect();this.hc.disconnect();this.dc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.Ud=class extends Z{constructor(b,a,c,d,e,f){super(b);this.R="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(){}};
self.Td=class extends Z{constructor(b,a,c){super(b);this.R="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.zd=new Float32Array(this.l.frequencyBinCount);this.Nd=new Uint8Array(a);this.Ld=this.Ua=0;b=this.s;b.Ma.add(this);T(b)}j(){this.s.Ma.delete(this);this.l.disconnect();super.j()}Ka(){this.l.getFloatFrequencyData(this.zd);this.l.getByteTimeDomainData(this.Nd);const b=this.l.fftSize;let a=this.Ua=0;for(var c=0;c<b;++c){let d=(this.Nd[c]-
128)/128;0>d&&(d=-d);this.Ua<d&&(this.Ua=d);a+=d*d}c=self.ab.pe;this.Ua=c(this.Ua);this.Ld=c(Math.sqrt(a/b))}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(){}};
